### ISSUE TITLE
Keep an eye out for the stable release

### ISSUE THREAD

**Issue by agibsonccc** [USCDataScience/dl4j-kerasimport-examples#1]
Thanks for doing this! We will be publishing a stable release soon pending our new transform learning api and some other stuff. Once that drops please update this repo with the stable release.

@turambar and @eraly worked on this if you'd like to update the credits as well.

**Comment by thammegowda** [comment]
Yes, I am watching the DL4J releases and I will update this repo when the new version goes to maven repo.
In fact, I have plans to add this functionality to our existing JVM based systems like Apache Tika ( https://wiki.apache.org/tika/TikaAndVision and Sparkler (https://github.com/USCDataScience/sparkler). Thanks to you for your work on deeplearning4j👍

**Comment by said120276** [comment]
HI;
thanks for that work.
I found that in your data file :inception-model-weights.h5 . the layer params names are of type : gamma,beta ,mean,std . But in DL4J "class KerasBatchNormalization" they use : gamma,beta ,running-mean,running-std ;
And when I change them manually in the class  the program work fine.

**Comment by thammegowda** [comment]
The examples are updated to stable version 0.8.0.
