### ISSUE TITLE
InvalidKerasConfigurationException

### ISSUE THREAD

**Issue by Emr03** [USCDataScience/dl4j-kerasimport-examples#3]
When I run the code I get a ClassNotFoundException for InvalidKerasConfigurationException. 
Any idea why? Is it currently possible to use pre-trained models such as InceptionV3 or VGG16 in DL4J? That would be incredibly useful. 

Thank you

**Comment by thammegowda** [comment]
> I get a ClassNotFoundException for InvalidKerasConfigurationException.

Looks like you have issue with your build setup  or IDE is not adding the classes to classPath.
How are you running it?
Are you able to run code using `mvn` as in https://github.com/USCDataScience/dl4j-kerasimport-examples/tree/master/dl4j-import-example#example-usage

> Is it currently possible to use pre-trained models such as InceptionV3 or VGG16 in DL4J? That would be incredibly useful.

Yes! Thats exactly what this repository is trying to achieve

**Comment by chrismattmann** [comment]
looks like this is fixed now...
