### ISSUE TITLE
predict result not as same as tensorflow's inceptionV3

### ISSUE THREAD

**Issue by jasstionzyf** [USCDataScience/dl4j-kerasimport-examples#5]
when i debug this inceptionv3 example , i find the flatten layer output is not same as tensorflow flatten output, for tensorflow's output is all above 0, but it is not,  some of the features < 0
also the predict result is not as good as tensorflow.
does above is normal? 
or can you give me some advices to change the code to make them generate same result (means generate same flatten layer's 2048 features ouput)?

**Comment by chrismattmann** [comment]
cc @thammegowda any idea here?

**Comment by thammegowda** [comment]
Our model is based on keras . It is not the same as the one Google released with tensorflow. Well, the architecture is same but the implementation and checkpoint state are different. Here is link to the model from which we extracted the weights https://github.com/fchollet/deep-learning-models/blob/8d8f54a9e1482c3642a55a694c2cde8f26562a06/inception_v3.py

**Comment by chrismattmann** [comment]
thanks @thammegowda
